---
- hosts: localhost
  vars_prompt:
    - name: "git_user_email"
      prompt: "what is your git email?"
      default: "victor.0w3@gmail.com"
      private: no
    - name: "git_user_name"
      prompt: "what is your git user?"
      default: "Victor Igor"
      private: no
  roles:
    - { role: dotfiles, tags: ['dotfiles'] }
  vars:
    command_t_bundle: ext.bundle
    update_vim_bundle: true
    install_masochist_vim_dependencies: true
    install_nvim_dependencies: true
