#!/bin/bash

DOTFILES_ROOT=$(pwd)

# symlink dotfiles into home directory
install_dotfiles () {

    local overwrite_all=false backup_all=false skip_all=false

    for src in $(find "$DOTFILES_ROOT/" -maxdepth 2 -name '*.symlink')
    do
        dst="$HOME/$(basename "${src%.*}")"
        ln -s "$src" "$dst"
    done
}

install_dotfiles

#setup oh-my-zsh
git clone https://github.com/robbyrussell/oh-my-zsh ~/.oh-my-zsh
